# Site settings
title: João Sabino - Security Analyst
description: "Um blog para compartilhar e contribuir"
baseurl: ""
url: "https://joaosabinon.github.io" 

# User settings
username: João Sabino
user_title: João Sabino - Security Analyst
email: joao.nsabino@gmail.com
twitter_username: JoaoSabinon
github_username:  joaosabinon
gplus_username:  loremipsum
linkedin_public_url: joao-sabino
disqus_username: 
profile_picture: https://raw.githubusercontent.com/s2b1n0/s2b1n0.github.io/master/perfil.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/s2b1n0
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: sherlock holmes web fuzzer
    url: https://github.com/joaosabinon/SherlockHolmesWebFuzzer
  - name: crt.sh resolve
    url: https://github.com/joaosabinon/crt.sh-resolve

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
